version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - 5433:5432
